<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Viewer for the execution log documents generated by the plugin tasks.
 *
 * Lists the *.log files stored in <repo>/logs/ and allows reading them in
 * the browser or downloading them.
 *
 * @package    local_educaaragon
 * @author     3iPunt <https://www.tresipunt.com/>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @copyright  3iPunt <https://www.tresipunt.com/>
 */

require_once(__DIR__ . '/../../config.php');
global $CFG, $OUTPUT, $PAGE;

require_once($CFG->dirroot . '/local/educaaragon/lib.php');

require_login();

$context = context_system::instance();
require_capability('local/educaaragon:manageall', $context);

$file = optional_param('file', '', PARAM_FILE);
$download = optional_param('download', 0, PARAM_BOOL);

$PAGE->set_url('/local/educaaragon/logs.php');
$PAGE->set_pagelayout('admin');
$PAGE->set_context($context);
$PAGE->set_title(get_string('logs', 'local_educaaragon'));
$PAGE->set_heading(get_string('logs', 'local_educaaragon'));

// Validate repository configuration before showing anything.
$repositoryid = get_config('local_educaaragon', 'repository');
if ($repositoryid === false) {
    echo $OUTPUT->header();
    echo $OUTPUT->notification(get_string('no_repository_select', 'local_educaaragon'), 'error');
    echo $OUTPUT->footer();
    exit;
}

$repository = get_repository();
$logsdir = rtrim($repository->get_rootpath(), '/') . '/logs/';

// View or download a single log file.
if ($file !== '') {
    $filename = basename($file);
    if ($filename !== $file || !preg_match('/^[A-Za-z0-9\-_]+\.log$/', $filename)) {
        throw new invalid_parameter_exception('Invalid log file name: ' . $file);
    }
    $filepath = $logsdir . $filename;
    if (!is_file($filepath)) {
        echo $OUTPUT->header();
        echo $OUTPUT->notification(get_string('logs_notfound', 'local_educaaragon'), 'error');
        echo $OUTPUT->continue_button(new moodle_url('/local/educaaragon/logs.php'));
        echo $OUTPUT->footer();
        exit;
    }
    if ($download) {
        send_file($filepath, $filename, 0, 0, false, true);
        exit;
    }
    $content = file_get_contents($filepath);
    echo $OUTPUT->header();
    echo $OUTPUT->heading(get_string('logs', 'local_educaaragon'));
    echo html_writer::start_div('mt-3 mb-2');
    echo html_writer::link(
        new moodle_url('/local/educaaragon/logs.php'),
        '« ' . get_string('logs_back', 'local_educaaragon'));
    echo html_writer::tag('strong', ' ' . $filename, ['class' => 'ml-3']);
    echo html_writer::link(
        new moodle_url('/local/educaaragon/logs.php', ['file' => $filename, 'download' => 1]),
        get_string('logs_download', 'local_educaaragon'),
        ['class' => 'btn btn-secondary btn-sm ml-3']);
    echo html_writer::end_div();
    echo html_writer::tag('pre', s($content), ['class' => 'pre-scrollable border p-2 bg-light']);
    echo local_educaaragon_version_footer();
    echo $OUTPUT->footer();
    exit;
}

// List the available log files, most recent first.
$logfiles = [];
if (is_dir($logsdir)) {
    foreach (glob($logsdir . '*.log') as $logfilepath) {
        $logfiles[] = [
            'name' => basename($logfilepath),
            'size' => filesize($logfilepath),
            'modified' => filemtime($logfilepath),
        ];
    }
}
usort($logfiles, function($a, $b) {
    return $b['modified'] <=> $a['modified'];
});

echo $OUTPUT->header();
echo $OUTPUT->heading(get_string('logs', 'local_educaaragon'));
echo html_writer::tag('p', get_string('logs_desc', 'local_educaaragon'));

if (empty($logfiles)) {
    echo $OUTPUT->notification(get_string('logs_empty', 'local_educaaragon'), 'info');
} else {
    $table = new html_table();
    $table->head = [
        get_string('logs_file', 'local_educaaragon'),
        get_string('logs_modified', 'local_educaaragon'),
        get_string('logs_size', 'local_educaaragon'),
        get_string('actions', 'moodle'),
    ];
    $table->attributes['class'] = 'generaltable';
    foreach ($logfiles as $logfile) {
        $viewurl = new moodle_url('/local/educaaragon/logs.php', ['file' => $logfile['name']]);
        $downloadurl = new moodle_url('/local/educaaragon/logs.php', ['file' => $logfile['name'], 'download' => 1]);
        $table->data[] = [
            html_writer::link($viewurl, $logfile['name']),
            userdate($logfile['modified'], get_string('strftimedatetimeshort', 'core_langconfig')),
            display_size($logfile['size']),
            html_writer::link($downloadurl, get_string('logs_download', 'local_educaaragon')),
        ];
    }
    echo html_writer::table($table);
}

echo local_educaaragon_version_footer();
echo $OUTPUT->footer();
